apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusters.engine.azkube.io
spec:
  group: engine.azkube.io
  names:
    kind: Cluster
    plural: clusters
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clientID:
              type: string
            clientSecret:
              type: string
            dnsPrefix:
              type: string
            location:
              type: string
            resourceGroupName:
              type: string
            subscriptionID:
              type: string
            tenantID:
              type: string
          type: object
        status:
          properties:
            adminKubeConfig:
              type: string
            bootstrapToken:
              type: string
            caCertificate:
              type: string
            caCertificateKey:
              type: string
            customerKubeConfig:
              type: string
            discoveryHashes:
              items:
                type: string
              type: array
            etcdCACertificate:
              type: string
            etcdCACertificateKey:
              type: string
            frontProxyCACertificate:
              type: string
            frontProxyCACertificateKey:
              type: string
            provisioningState:
              type: string
            publicIPAddress:
              type: string
            serviceAccountKey:
              type: string
            serviceAccountPub:
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
