apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: nodesets.engine.azk.io
spec:
  group: engine.azk.io
  names:
    kind: NodeSet
    plural: nodesets
  scope: Namespaced
  subresources:
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            kubernetesVersion:
              type: string
            replicas:
              format: int32
              type: integer
            vmSKUType:
              type: string
          type: object
        status:
          properties:
            kubeConfig:
              type: string
            kubernetesVersion:
              type: string
            nodeStatus:
              items:
                properties:
                  vmComputerName:
                    type: string
                  vmInstanceID:
                    type: string
                type: object
              type: array
            provisioningState:
              type: string
            replicas:
              format: int32
              type: integer
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
