
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: clusters.engine.azk.io
spec:
  group: engine.azk.io
  names:
    kind: Cluster
    plural: clusters
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Cluster is the Schema for the clusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ClusterSpec defines the desired state of Cluster
          properties:
            adminKubeConfig:
              type: string
            azureCloudProviderConfig:
              type: string
            bootstrapKubernetesVersion:
              type: string
            bootstrapVMSKUType:
              type: string
            caCertificate:
              type: string
            caCertificateKey:
              type: string
            clientID:
              type: string
            clientSecret:
              type: string
            cloud:
              type: string
            clusterName:
              type: string
            customerKubeConfig:
              type: string
            discoveryHashes:
              items:
                type: string
              type: array
            dnsPrefix:
              type: string
            etcdCACertificate:
              type: string
            etcdCACertificateKey:
              type: string
            frontProxyCACertificate:
              type: string
            frontProxyCACertificateKey:
              type: string
            groupLocation:
              type: string
            groupName:
              type: string
            internalDNSName:
              type: string
            publicDNSName:
              type: string
            publicIPAddress:
              type: string
            serviceAccountKey:
              type: string
            serviceAccountPub:
              type: string
            subscriptionID:
              type: string
            tenantID:
              type: string
            userAgent:
              type: string
          type: object
        status:
          description: ClusterStatus defines the observed state of Cluster
          properties:
            provisioningState:
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
