
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: nodesets.engine.azk.io
spec:
  group: engine.azk.io
  names:
    kind: NodeSet
    plural: nodesets
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NodeSet is the Schema for the nodesets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NodeSetSpec defines the desired state of NodeSet
          properties:
            kubernetesVersion:
              type: string
            replicas:
              format: int32
              type: integer
            vmSKUType:
              type: string
          type: object
        status:
          description: NodeSetStatus defines the observed state of NodeSet
          properties:
            kubeConfig:
              type: string
            kubernetesVersion:
              type: string
            nodeStatus:
              items:
                properties:
                  vmComputerName:
                    type: string
                  vmInstanceID:
                    type: string
                type: object
              type: array
            provisioningState:
              type: string
            replicas:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
